version: "3.9"

services:
  tgvid-comp-bot:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: tgvid-comp
    environment:
      - APP_ID=${APP_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER=${OWNER}
      - THUMBNAIL=${THUMBNAIL}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always